### ISSUE TITLE
Status 0 or 1

### ISSUE THREAD

**Issue by opensource-emr** [opensource-emr/Telemedicine#1]
Status 0 and 1.

**Comment by opensource-emr** [comment]
Status 1 indicates that the doctor is currently speaking with the patient. I understand that 1/0 looks odd. So we will display the current patient name at the top with whom the doctor is speaking. Status will be removed from the grid , the patient with whom the current discussion is doing will mark as green. Let me know this look like.

![image](https://user-images.githubusercontent.com/48054642/78358182-5fda2280-75d0-11ea-9b84-c7807091530f.png)

**Comment by Binod888** [comment]
> Status 1 indicates that the doctor is currently speaking with the patient. I understand that 1/0 looks odd. So we will display the current patient name at the top with whom the doctor is speaking. Status will be removed from the grid , the patient with whom the current discussion is doing will mark as green. Let me know this look like.
> 
> ![image](https://user-images.githubusercontent.com/48054642/78358182-5fda2280-75d0-11ea-9b84-c7807091530f.png)

also change Patinet completed to Complete Visit.

**Comment by opensource-emr** [comment]
Status has been removed for confusing.
