### ISSUE TITLE
Scattered waiting 

### ISSUE THREAD

**Issue by swapnil1010** [opensource-emr/Telemedicine#10]
If lots of patients waiting on queue, doctor have no any idea which patient should be checked first so we should assign proper unique serial number or visitor number to every patient

**Comment by FaveDoc** [comment]
or, patient identifiers like email or phone no can be added. The patient can be called at a later time if missed appt.

**Comment by opensource-emr** [comment]
A running ID has been added which indicates which is the first patient which comes in.
