### ISSUE TITLE
Azure Appservice Deployment Issue

### ISSUE THREAD

**Issue by RahulSapkota** [opensource-emr/Telemedicine#113]
Hi,
The App is working fine in local for both provider and patient. but when the same thing is deployed in Azure app service the patient portal is not loading the video and chat. 

But the developer tool log in browser shows the wws: websocket is connected.
Please provide help on resolution of this issue.

**Comment by opensource-emr** [comment]
In Azure app enable Socket , this code uses signalr for chats
