### ISSUE TITLE
Duplicate patient

### ISSUE THREAD

**Issue by opensource-emr** [opensource-emr/Telemedicine#2]
If the patient logs in and disconnects in between and if he logs in again. Multiple entries of the patient is seen as shown in the figure below. We should have a idle time which should be displayed where in patients which are above 1 minute idle should be removed. Idle means he has close the browser of telemedicine.

![image](https://user-images.githubusercontent.com/48054642/78358410-c52e1380-75d0-11ea-8e8c-3b127c0931a3.png)

**Comment by Binod888** [comment]
> If the patient logs in and disconnects in between and if he logs in again. Multiple entries of the patient is seen as shown in the figure below. We should have a idle time which should be displayed where in patients which are above 1 minute idle should be removed. Idle means he has close the browser of telemedicine.
> 
> ![image](https://user-images.githubusercontent.com/48054642/78358410-c52e1380-75d0-11ea-8e8c-3b127c0931a3.png)

need to add a few more identifiers, like Age, sex, etc. Once the visit completed, it should show up in a different section of the screen.

**Comment by opensource-emr** [comment]
Duplicate patient can not login and if the patient closes the browser , after 25 seconds the patient is moved from the waiting room.
