### ISSUE TITLE
Build, Run and Deploy

### ISSUE THREAD

**Issue by malakhovks** [opensource-emr/Telemedicine#68]
Hi! I am very interested in your project.
But I am confused about how to build, run and deploy it.
No problem with Angular frontend part. The main problem with backend and database parts.
Do you have more distinct **build and running step by step guide**?

**Comment by malakhovks** [comment]
Okay I run the project :) But how I can register or login as a doctor/patient?

**Comment by malakhovks** [comment]
For login I use basic credentials (login: admin, password: admin)
but I receive the `null` exception in file **SecurityController.cs**:
```
var pro = _providerRepository.getProviderByUserName(provider.userName); 
```
Need help with that.

**Comment by opensource-emr** [comment]
In Database have your configured the provider and practice tables properly.

**Comment by malakhovks** [comment]
> In Database have your configured the provider and practice tables properly.

Of course **No**, cause in your guide no any info about this.
So can you tell me briefly what I need to do?

**Comment by opensource-emr** [comment]
Yeah we did not provide any guide . We are working on it. Do send a mail shiv_koirala@yahoo.com i will connect you with some one from dev team. Thanks

**Comment by malakhovks** [comment]
> Yeah we did not provide any guide . We are working on it. Do send a mail [shiv_koirala@yahoo.com](mailto:shiv_koirala@yahoo.com) i will connect you with some one from dev team. Thanks

I already send an email to this address [shiv_koirala@yahoo.com](mailto:shiv_koirala@yahoo.com) from [malakhovks@nas.gov.ua](mailto:malakhovks@nas.gov.ua)
Please answer me :)

**Comment by malakhovks** [comment]
Thanks for your help!
